# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/FPGAProject/TASK/Project/Project.srcs/sources_1/ip/blk_mem_gen_sin/blk_mem_gen_sin.xci
# IP: The module: 'blk_mem_gen_sin' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGAProject/TASK/Project/Project.gen/sources_1/ip/blk_mem_gen_sin/blk_mem_gen_sin_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_sin'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/FPGAProject/TASK/Project/Project.srcs/sources_1/ip/blk_mem_gen_sin/blk_mem_gen_sin.xci
# IP: The module: 'blk_mem_gen_sin' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGAProject/TASK/Project/Project.gen/sources_1/ip/blk_mem_gen_sin/blk_mem_gen_sin_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_sin'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
